### ISSUE TITLE
error：from snli import SNLI

### ISSUE THREAD

**Issue by vencent-debug** [sharan21/disentangled-style-transfer-vae#1]
snli:ModuleNotFoundError: No module named 'snli'
pip install snli is workless
and FileExistsError: [Errno 17] File exists: './data/mutlitask'

**Comment by sharan21** [comment]
Hey, sorry there were bugs and inaccuracies in the earlier version. I have added major changes to this repo and hopefully, now it should be working. Otherwise please add an issue and I will fix It quickly.
