### ISSUE TITLE
An issue about word2vec

### ISSUE THREAD

**Issue by cloudyskyy** [sharan21/disentangled-style-transfer-vae#3]
Really thankful for your replication of the paper's code! Just wondering the word2vec file in your implemention. Are they trained on the yelp dataset with gensim?

**Comment by cloudyskyy** [comment]
alright，I've solved the question by trainings the word2vec on the dataset with gensim.

**Comment by sharan21** [comment]
hey! thanks for looking into this, please add a PR to merge your code to train word2vec with gensim. I will add it in case others have an issue with this. Thanks.
