### ISSUE TITLE
How to get sentiment.train.0

### ISSUE THREAD

**Issue by tianjunyu0871** [sharan21/disentangled-style-transfer-vae#6]
Could you please tell me how to get the sentiment.train.0. thanks
![image](https://user-images.githubusercontent.com/55222964/166127550-8f8b04ae-1818-405d-8eb6-e48607b828c1.png)

**Comment by NaveenKinnal** [comment]
You can download the data from here -https://github.com/shentianxiao/language-style-transfer/tree/master/data/yelp
