### ISSUE TITLE
Does this code work?

### ISSUE THREAD

**Issue by xdc-hub** [sharan21/disentangled-style-transfer-vae#8]
Dear professor，Can this be implemented now? Is it possible to implement the function of the previous tensorflow code, thanks

**Comment by sharan21** [comment]
This code is NOT usable so please avoid trying to build using it. There are issues with the underlying RNN code whcih prevents the model from performing even a simple reconstruction task properly. The issue does not seem to be with the code related to the additional discriminators and auxillary losses. I have not found time to fix this and moved along to other things quite some time back. If you wish to work over this and correct it, please consider looking into fixing the underlying RNN. I am writing this to avoid any wastage of time for researchers, considering that I have been emailed quite a bit about if this is usable. I have updated the readme to convey this.

**Comment by xdc-hub** [comment]
Thank you for your reply. I didn't expect you to reply so quickly. I'm sorry to bother you. I'll give it a try. If it can be fixed, I'll let you know as soon as possible.
